"""astropy: Specialized changes -- 25 rules.

Layer C. Every rule is two layers (docs/checker-authoring.md §2): ``precondition`` selects on
the rule's ANTECEDENT, ``pass_condition`` grades.

This is the pack's long tail, and its shape is worth stating plainly: **most of these rules
will never fire on a bug-fix benchmark.** Cython extensions, bundled C libraries,
installable headers, command-line scripts and package data are things astropy legislates
carefully and a SWE-bench instance almost never touches. A rule that finds no target is
dropped from the score entirely (§2.1), so the cost of that is an honest activation rate,
not a distorted one -- and writing them is what makes the activation rate a finding rather
than an assumption.

**Two antecedents are shared and are worth naming once.**

*A new optional dependency* (C018, C019) is not observable. It is approximated by the shape
astropy gives one: a third-party package imported inside a function or behind a ``try``,
plus any ``HAS_*`` flag the contribution adds. Both rules select on it and disagree only
about where the declaration must appear.

*A Cython or C extension* (C122-C127, C225-C230) is approximated by the files a
contribution adds -- ``.pyx``, ``.c``, ``.h``, ``setup_package.py`` -- because the build
system is not run here. Each rule says which file made it fire.

**C124's licence condition is not checkable and is declared rather than dropped.** Whether
an external library's licence permits bundling is a fact about that library; the rule is
graded on the bundling and the condition is stated in its docstring.
"""

from __future__ import annotations

import ast
import re
from typing import Iterator

from compliance.core import ownership as own
from compliance.core.models import (EvidenceBundle, Satisfied, Target, Undetermined,
                                    Violated)
from compliance.core.registry import rule
from compliance.extractors import python_ast as pa
from compliance.rules.astropy._common import (CORE_IMPORTABLE, DECLARED_DEPENDENCIES,
                                              OPTIONAL_DEPS, PACKAGE, PYPROJECT,
                                              added_text, documentation_files,
                                              is_source_path, modules, target)

CATEGORY = "Specialized changes"

SETUP_PACKAGE = "setup_package.py"
CEXTERN = "cextern/"
DATA_DIR = "/data/"
INCLUDE_DIR = "/include/"
USE_SYSTEM = re.compile(r"\bASTROPY_USE_SYSTEM_[A-Z0-9_]+\b")
PACKAGE_DATA_SECTION = "[tool.setuptools.package_data]"
GET_EXTENSIONS = "get_extensions"
#: The hash form astropy's data machinery pins a version with, e.g.
#: ``get_pkg_data_filename('hash/94935ac31d585f68041c08f87d1a19d4')``.
HASH_FORM = re.compile(r"\bhash/[0-9a-f]{8,}\b")
PKG_DATA_ACCESSORS = ("get_pkg_data_fileobj", "get_pkg_data_filename",
                      "get_pkg_data_contents", "get_pkg_data_path", "get_pkg_data_filenames")
REMOTE_ACCESSORS = ("download_file", "get_readable_fileobj", "get_file_contents")
CONFIG_ITEM = ("ConfigItem", "ConfigNamespace")
#: Ways to persist configuration that are not astropy's mechanism.
OTHER_CONFIG = ("configparser.ConfigParser", "ConfigParser", "json.dump", "yaml.dump",
                "pickle.dump", "shelve.open")

#: Extensions of files that ship as package data rather than as code.
CODE_SUFFIXES = (".py", ".pyx", ".pxd", ".c", ".h", ".cpp", ".rst", ".md", ".txt",
                 ".toml", ".cfg", ".in", ".yml", ".yaml")
DATA_SUFFIXES = (".fits", ".dat", ".csv", ".ecsv", ".json", ".xml", ".vot", ".hdr",
                 ".fit", ".gz", ".npy", ".npz", ".hdf5", ".tbl", ".par", ".db")
#: About 100 kB, the ceiling codeguide states. "About" is the source's own hedge.
DATA_SIZE_LIMIT = 100 * 1024

CYTHON_GENERATED = re.compile(r"Generated by Cython", re.I)
#: An include of a header that is not the C standard library's.
NON_STANDARD_INCLUDE = re.compile(r'^\s*#include\s+[<"]([A-Za-z0-9_./-]+)[>"]', re.M)
STANDARD_HEADERS = frozenset("""
stdio.h stdlib.h string.h math.h stddef.h stdint.h stdbool.h limits.h float.h time.h
errno.h assert.h ctype.h locale.h setjmp.h signal.h stdarg.h wchar.h wctype.h complex.h
Python.h structmember.h
""".split())


def _tail(name: str, n: int = 2) -> str:
    return ".".join(name.split(".")[-n:])


def _authored(bundle: EvidenceBundle, path: str) -> frozenset[int]:
    change = bundle.files.get(path)
    return change.authored_lines if change else frozenset()


def _library_modules(bundle: EvidenceBundle) -> list[tuple[str, pa.PyModule]]:
    return [(p, m) for p, m in modules(bundle) if is_source_path(p)]


def _written_calls(bundle: EvidenceBundle) -> Iterator[tuple[str, pa.PyModule, pa.CallSite]]:
    for path, module in _library_modules(bundle):
        authored = _authored(bundle, path)
        for call in module.calls:
            if call.lineno in authored:
                yield path, module, call


def _is_third_party(name: str) -> bool:
    import sys

    return bool(name) and name not in CORE_IMPORTABLE and name not in sys.stdlib_module_names


def _in_try(module: pa.PyModule, lineno: int) -> bool:
    return any(node.lineno <= lineno <= getattr(node, "end_lineno", node.lineno)
               for node in module.tries)


def _optional_dependencies(bundle: EvidenceBundle) -> dict[str, tuple[str, int]]:
    """Packages the contribution treats as optional, by name.

    The observable face of *a new optional dependency*: a third-party package imported
    inside a function or behind a ``try`` -- astropy's two sanctioned shapes for one --
    together with any ``HAS_*`` flag the contribution adds to ``optional_deps``. A package
    already in astropy's declared dependency list is not new and is left out.
    """
    found: dict[str, tuple[str, int]] = {}
    for path, module in _library_modules(bundle):
        authored = _authored(bundle, path)
        for site in module.import_sites:
            if site.lineno not in authored:
                continue
            head = site.origin.split(".")[0]
            if not _is_third_party(head):
                continue
            if head.lower().replace("-", "_") in {d.lower().replace("-", "_")
                                                  for d in DECLARED_DEPENDENCIES}:
                continue
            inside = module.enclosing_function(site.lineno) is not None
            if inside or _in_try(module, site.lineno):
                found.setdefault(head, (path, site.lineno))
    for name, lineno in _has_flags(bundle).items():
        found.setdefault(name.lower(), (OPTIONAL_DEPS, lineno))
    return found


def _has_flags(bundle: EvidenceBundle) -> dict[str, int]:
    """``HAS_X`` flags the contribution adds to ``optional_deps.py``."""
    out: dict[str, int] = {}
    change = bundle.files.get(OPTIONAL_DEPS)
    if change is None:
        return out
    for lineno, text in change.added_lines:
        if match := re.match(r"\s*HAS_([A-Z0-9_]+)\s*=", text):
            out[match.group(1)] = lineno
        for match in re.finditer(r'"([A-Za-z0-9_]+)"|\'([A-Za-z0-9_]+)\'', text):
            name = match.group(1) or match.group(2)
            if name.isupper() or name.islower():
                out.setdefault(name.upper(), lineno)
    return out


def _added_paths(bundle: EvidenceBundle, predicate) -> list[str]:
    return [p for p in sorted(bundle.files)
            if predicate(p) and own.owns_file(bundle, p, "created")]


def _touched_paths(bundle: EvidenceBundle, predicate) -> list[str]:
    return [p for p in sorted(bundle.files)
            if predicate(p) and own.owns_file(bundle, p, "touched")]


def _is_data_file(path: str) -> bool:
    return (path.startswith(PACKAGE) and not path.endswith(CODE_SUFFIXES)
            and (path.endswith(DATA_SUFFIXES) or DATA_DIR in path))


def _is_setup_package(path: str) -> bool:
    return path.rsplit("/", 1)[-1] == SETUP_PACKAGE


def _extension_calls(bundle: EvidenceBundle) -> Iterator[tuple[str, pa.PyModule, pa.CallSite]]:
    """``Extension(...)`` constructions the agent wrote in a ``setup_package.py``."""
    for path, module in modules(bundle):
        if not _is_setup_package(path):
            continue
        authored = _authored(bundle, path)
        for call in module.calls:
            if call.lineno in authored and call.func.split(".")[-1] == "Extension":
                yield path, module, call


def _string_args(call: pa.CallSite) -> list[str]:
    """Every string literal anywhere in a call's arguments."""
    out: list[str] = []
    for node in list(call.args) + list(call.keywords.values()):
        for child in ast.walk(node):
            if isinstance(child, ast.Constant) and isinstance(child.value, str):
                out.append(child.value)
    return out


def _is_script_module(path: str, module: pa.PyModule) -> bool:
    """A module runnable from the command line, which is what the scripts guide is about."""
    if not is_source_path(path):
        return False
    if "/scripts/" in path:
        return True
    return any(isinstance(node, ast.If) and "__main__" in ast.dump(node.test)
               for node in module.tree.body)


def _packaging_text(bundle: EvidenceBundle) -> str:
    text = ""
    for path in (PYPROJECT, "setup.cfg", "setup.py"):
        change = bundle.files.get(path)
        if change is not None:
            text += (change.head_text or "") + "\n" + added_text(bundle, path) + "\n"
    return text


def _documentation_text(bundle: EvidenceBundle) -> str:
    """Everything the contribution wrote into the manual, plus every docstring it wrote."""
    text = "\n".join(added_text(bundle, path) for path in documentation_files(bundle))
    for path, module in modules(bundle):
        authored = _authored(bundle, path)
        for doc in module.docstrings:
            if any(lineno in authored for lineno, _ in doc.lines()):
                text += "\n" + doc.text
    return text


# --- optional dependencies ------------------------------------------------------------


@rule(
    id="ASTROPY-C018",
    category=CATEGORY,
    ownership="touched",  # spec §4.3 -- the antecedent is code the agent edited (§4.2)
    reads=("files",),  # spec §5: both the import and optional_deps.py are in the patch
    heuristic=True,
)
class NewOptionalDependencyGetsAHasFlag:
    """Pre-condition: each package the contribution treats as an optional dependency.
    Pass condition: ``astropy/utils/compat/optional_deps.py`` gains a ``HAS_*`` flag for it.

    Heuristic on the **pre-condition** (§6.3): *a new optional dependency* is not written
    anywhere, so it is approximated by the shape astropy gives one -- a third-party package
    imported inside a function or behind a ``try``, and not already among astropy's declared
    dependencies. A dependency introduced some other way is not selected.

    Firing on the flag instead of on the dependency would be §7.1 inverted: an agent that
    added neither would find no target and be recorded as compliant.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        return [target(f"has-flag:{name}", path, (lineno, lineno), (name, path, lineno, b),
                       f"optional dependency {name}")
                for name, (path, lineno) in sorted(_optional_dependencies(b).items())]

    def pass_condition(self, t: Target):
        name, path, lineno, bundle = t.payload
        flags = _has_flags(bundle)
        if name.upper() in flags:
            return Satisfied(f"HAS_{name.upper()} added to {OPTIONAL_DEPS}")
        return Violated(f"{path}:{lineno} introduces the optional dependency `{name}` and "
                        f"no HAS_{name.upper()} flag is added to {OPTIONAL_DEPS}")


@rule(
    id="ASTROPY-C019",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5: pyproject.toml is a file in the patch
    heuristic=True,
)
class NewOptionalDependencyIsInPyproject:
    """Pre-condition: each package the contribution treats as an optional dependency.
    Pass condition: ``pyproject.toml`` names it under ``[project.optional-dependencies]``.

    Same approximated antecedent as C018 and the same reason for it (§6.3). The grading
    differs: the sentence names two groups, ``all`` for runtime use and ``test_all`` for
    test-only use, and either is accepted because which one applies depends on where the
    dependency is used -- a distinction the patch shows only weakly.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        return [target(f"pyproject-dep:{name}", path, (lineno, lineno),
                       (name, path, lineno, b), f"optional dependency {name}")
                for name, (path, lineno) in sorted(_optional_dependencies(b).items())]

    def pass_condition(self, t: Target):
        name, path, lineno, bundle = t.payload
        change = bundle.files.get(PYPROJECT)
        text = ((change.head_text or "") + added_text(bundle, PYPROJECT)) if change else ""
        if "optional-dependencies" in text and re.search(rf"\b{re.escape(name)}\b", text,
                                                         re.I):
            return Satisfied(f"`{name}` appears under [project.optional-dependencies]")
        return Violated(f"{path}:{lineno} introduces the optional dependency `{name}` and "
                        f"{PYPROJECT} does not record it under "
                        f"[project.optional-dependencies]")


@rule(
    id="ASTROPY-C078",
    category=CATEGORY,
    ownership="touched",  # spec §4.3 -- the import sits in code the agent edited
    reads=("files",),  # spec §5: the documentation is in the patch too
    heuristic=True,
)
class AdditionalDependenciesAreDocumented:
    """Pre-condition: each third-party package the agent's written code introduces into a
    sub-module or function.
    Pass condition: the contribution's documentation mentions it.

    Heuristic on **both layers** (§6.1). The pre-condition reads an added import as
    "introduces a dependency", which over-fires when the package was already used
    elsewhere in the sub-module. The pass condition accepts a mention anywhere in the
    manual pages or docstrings the contribution wrote, which is weaker than "noted in the
    package documentation" and cannot see documentation the contribution did not touch.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        seen: dict[str, tuple[str, int]] = {}
        for path, module in _library_modules(b):
            authored = _authored(b, path)
            for site in module.import_sites:
                if site.lineno not in authored:
                    continue
                head = site.origin.split(".")[0]
                if _is_third_party(head):
                    seen.setdefault(head, (path, site.lineno))
        return [target(f"doc-dep:{name}", path, (lineno, lineno), (name, path, lineno, b),
                       f"imports {name}")
                for name, (path, lineno) in sorted(seen.items())]

    def pass_condition(self, t: Target):
        name, path, lineno, bundle = t.payload
        if re.search(rf"\b{re.escape(name)}\b", _documentation_text(bundle), re.I):
            return Satisfied(f"the contribution's documentation mentions `{name}`")
        return Violated(f"{path}:{lineno} introduces the third-party dependency `{name}` "
                        f"and no documentation in the contribution mentions it")


@rule(
    id="ASTROPY-C080",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5
    heuristic=True,
)
class OptionalDependenciesAreImportedInTheFunction:
    """Pre-condition: each import of a third-party package the agent wrote in library code.
    Pass condition: it is a plain ``import`` statement inside the function or method that
    uses it.

    Selecting every third-party import, rather than the module-level ones, is what lets a
    correctly placed import record a pass (§7.1). An import behind a ``try`` is a violation
    here: the sentence asks for a plain statement precisely so the ``ImportError`` reaches
    the user.

    Heuristic on the **pre-condition** (§6.3): *optional* is approximated by *third-party*.
    A required third-party dependency imported at module level is selected here and is not
    what the sentence is about -- which is why C077, whose subject is exactly that, is a
    separate rule.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        out = []
        for path, module in _library_modules(b):
            authored = _authored(b, path)
            for site in module.import_sites:
                if site.lineno not in authored:
                    continue
                head = site.origin.split(".")[0]
                if not _is_third_party(head):
                    continue
                inside = module.enclosing_function(site.lineno)
                out.append(target(f"optional-import:{path}:{site.lineno}", path,
                                  (site.lineno, site.lineno),
                                  (path, site.lineno, head, inside is not None,
                                   _in_try(module, site.lineno)),
                                  f"import {head}"))
        return out

    def pass_condition(self, t: Target):
        path, lineno, head, in_function, guarded = t.payload
        if not in_function:
            return Violated(f"{path}:{lineno} imports the optional dependency `{head}` at "
                            f"module level rather than inside the function that uses it")
        if guarded:
            return Violated(f"{path}:{lineno} imports `{head}` behind a try/except rather "
                            f"than with a plain import statement")
        return Satisfied(f"{path}:{lineno} imports `{head}` plainly, inside the function "
                         f"that uses it")


# --- package data ----------------------------------------------------------------------


@rule(
    id="ASTROPY-C091",
    category=CATEGORY,
    ownership="created",  # spec §4.1 -- where a data file goes is decided when it is added
    reads=("files",),  # spec §5: the path is the whole question
    heuristic=True,
)
class PackageDataLivesInADataDirectory:
    """Pre-condition: each data file the agent added inside ``astropy/``.
    Pass condition: it sits in a ``data`` directory inside its sub-package.

    Heuristic on the **pre-condition** (§6.3): *package data* is approximated by a file
    under the package that is not source, documentation or configuration. A data file with
    an unfamiliar extension placed outside a ``data`` directory is not selected, so the
    check under-reports rather than inventing violations.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        return [target(f"data-dir:{path}", path, None, path, path)
                for path in _added_paths(b, _is_data_file)]

    def pass_condition(self, t: Target):
        path = t.payload
        if DATA_DIR in path:
            return Satisfied(f"{path} is in a data directory inside its sub-package")
        return Violated(f"{path} is package data outside a `data` directory")


@rule(
    id="ASTROPY-C092",
    category=CATEGORY,
    ownership="created",  # spec §4.1
    reads=("files",),  # spec §5
    heuristic=True,
)
class DataFilesStayUnderAboutOneHundredKilobytes:
    """Pre-condition: each data file the agent added inside ``astropy/``.
    Pass condition: it is smaller than about 100 kB.

    Heuristic on the **pass condition** (§6.2): the bundle carries a file's reconstructed
    text, not its size on disk, so the text's length stands in for the byte count. A binary
    file the harness could not reconstruct is undetermined rather than passed -- reporting
    a file we cannot measure as small would be the silent pass §2.2 forbids.

    "About" is the source's own hedge and is kept: the limit is applied at 100 kB with no
    tolerance invented on either side.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        return [target(f"data-size:{path}", path, None, (path, b.files[path]), path)
                for path in _added_paths(b, _is_data_file)]

    def pass_condition(self, t: Target):
        path, change = t.payload
        if change.head_text is None:
            return Undetermined("parse_error",
                                f"{path} was not reconstructed, so its size is unknown")
        size = len(change.head_text.encode("utf-8", "replace"))
        if size > DATA_SIZE_LIMIT:
            return Violated(f"{path} is {size // 1024} kB, over the ~100 kB ceiling; it "
                            f"belongs outside the repository")
        return Satisfied(f"{path} is {size // 1024} kB")


@rule(
    id="ASTROPY-C093",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5
    heuristic=True,
)
class PackageDataIsReadThroughGetPkgData:
    """Pre-condition: each call the agent wrote that reaches a package data file.
    Pass condition: it goes through ``get_pkg_data_fileobj`` or ``get_pkg_data_filename``.

    Heuristic on the **pre-condition** (§6.3): *accessing package data* is approximated by
    a call carrying a string that names a data file or a ``data`` directory, plus the
    ``get_pkg_data_*`` calls themselves. Selecting only the raw ``open`` calls would make
    every target a violation (§7.1); selecting only the sanctioned ones would make every
    target a pass.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        out = []
        for path, module, call in _written_calls(b):
            short = call.func.split(".")[-1]
            literals = _string_args(call)
            names_data = any(text.endswith(DATA_SUFFIXES) or "data/" in text
                             for text in literals)
            if short in PKG_DATA_ACCESSORS or (names_data and short in
                                               ("open", "loadtxt", "genfromtxt", "read",
                                                "Path", "read_text", "read_bytes")):
                out.append(target(f"pkg-data:{path}:{call.lineno}", path,
                                  (call.lineno, call.lineno),
                                  (path, call.lineno, short), call.func))
        return out

    def pass_condition(self, t: Target):
        path, lineno, short = t.payload
        if short in PKG_DATA_ACCESSORS:
            return Satisfied(f"{path}:{lineno} reads package data through `{short}`")
        return Violated(f"{path}:{lineno} reads package data with `{short}` rather than "
                        f"get_pkg_data_fileobj or get_pkg_data_filename")


@rule(
    id="ASTROPY-C094",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5
    heuristic=True,
)
class SpecificDataVersionsArePinnedByHash:
    """Pre-condition: each call the agent wrote that fetches a remotely hosted data file.
    Pass condition: it names the file by the ``hash/...`` form, or passes a hash argument.

    Heuristic on the **pre-condition** (§6.3): the sentence's antecedent is *a specific
    version of a data file is needed*, which is an intention. It is approximated by
    fetching remote data at all, on the reading that a remote file whose content can change
    is exactly when the version matters. That over-fires on a fetch where any version will
    do.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        out = []
        for path, module, call in _written_calls(b):
            short = call.func.split(".")[-1]
            literals = _string_args(call)
            remote = any(text.startswith(("http://", "https://", "ftp://"))
                         or HASH_FORM.search(text) for text in literals)
            if short in REMOTE_ACCESSORS or (remote and short in PKG_DATA_ACCESSORS):
                out.append(target(f"data-hash:{path}:{call.lineno}", path,
                                  (call.lineno, call.lineno),
                                  (path, call.lineno, short, literals,
                                   sorted(call.keywords)), call.func))
        return out

    def pass_condition(self, t: Target):
        path, lineno, short, literals, keywords = t.payload
        if any(HASH_FORM.search(text) for text in literals):
            return Satisfied(f"{path}:{lineno} pins the data file by hash")
        if any(key in ("hashval", "sha256", "hash") for key in keywords):
            return Satisfied(f"{path}:{lineno} passes a hash argument to `{short}`")
        return Violated(f"{path}:{lineno} fetches a remote data file through `{short}` "
                        f"without the astropy.utils.data hash mechanism")


# --- configuration ------------------------------------------------------------------


def _config_calls(bundle: EvidenceBundle) -> Iterator[tuple[str, pa.PyModule, pa.CallSite,
                                                            bool]]:
    """Calls the agent wrote that persist configuration, and whether they are astropy's."""
    for path, module, call in _written_calls(bundle):
        resolved = module.origin(call.func)
        short = call.func.split(".")[-1]
        if short in CONFIG_ITEM:
            yield path, module, call, True
        elif short in [name.split(".")[-1] for name in OTHER_CONFIG] or _tail(
                resolved) in OTHER_CONFIG:
            yield path, module, call, False


@rule(
    id="ASTROPY-C095",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5
    heuristic=True,
)
class PersistentConfigurationUsesAstropyConfig:
    """Pre-condition: each place the agent's written code persists configuration.
    Pass condition: it does so through ``astropy.config`` -- a ``ConfigItem`` or a
    ``ConfigNamespace``.

    Heuristic on the **pre-condition** (§6.3): *persistent configuration* is approximated
    by the calls that write or declare it -- astropy's own two, and the general-purpose
    alternatives a contributor might reach for instead (``configparser``, a dumped JSON or
    YAML file, a pickle). A configuration mechanism outside that vocabulary is not
    selected.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        return [target(f"config:{path}:{call.lineno}", path, (call.lineno, call.lineno),
                       (path, call.lineno, call.func, is_astropy), call.func)
                for path, _, call, is_astropy in _config_calls(b)]

    def pass_condition(self, t: Target):
        path, lineno, func, is_astropy = t.payload
        if is_astropy:
            return Satisfied(f"{path}:{lineno} declares configuration with `{func}`")
        return Violated(f"{path}:{lineno} persists configuration through `{func}` rather "
                        f"than the astropy.config mechanism")


@rule(
    id="ASTROPY-C096",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5
    heuristic=True,
)
class ConfigurationItemsSitAtTheTopOfTheModule:
    """Pre-condition: each ``ConfigItem`` or ``ConfigNamespace`` the agent declared.
    Pass condition: it appears before the module's first function or class that is not a
    configuration namespace.

    Heuristic on the **pass condition** (§6.2): *the top of the module or package* is not
    a line number, and "before the first definition" stands in for it. A configuration item
    declared after a helper function but still visibly at the head of the file reads as a
    violation here.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        out = []
        for path, module, call, is_astropy in _config_calls(b):
            if not is_astropy:
                continue
            out.append(target(f"config-top:{path}:{call.lineno}", path,
                              (call.lineno, call.lineno),
                              (path, call.lineno, module), call.func))
        return out

    def pass_condition(self, t: Target):
        path, lineno, module = t.payload
        boundary = None
        for node in module.tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                boundary = node.lineno
                break
            if isinstance(node, ast.ClassDef):
                bases = [pa.dotted_name(b).split(".")[-1] for b in node.bases]
                if "ConfigNamespace" not in bases:
                    boundary = node.lineno
                    break
        if boundary is not None and lineno > boundary:
            return Violated(f"{path}:{lineno} declares a configuration item below the "
                            f"definition at line {boundary}, not at the top of the module")
        return Satisfied(f"{path}:{lineno} declares its configuration item at the top of "
                         f"the module")


@rule(
    id="ASTROPY-C224",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5
    heuristic=True,
)
class ConfigurationOptionsAreDocumented:
    """Pre-condition: each configuration option the agent added through ``astropy.config``.
    Pass condition: it carries a description, or the contribution's documentation mentions
    it.

    Heuristic on the **pass condition** (§6.2): "explicitly mentioned in the documentation"
    is accepted in two forms, because astropy's own machinery renders a ``ConfigItem``'s
    description into the manual -- so the description *is* the documentation for most
    items. A mention in a manual page the contribution did not touch cannot be seen.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        out = []
        for path, module, call, is_astropy in _config_calls(b):
            if not is_astropy or call.func.split(".")[-1] != "ConfigItem":
                continue
            names = [text for text in _string_args(call)]
            out.append(target(f"config-doc:{path}:{call.lineno}", path,
                              (call.lineno, call.lineno),
                              (path, call.lineno, call, names, b), call.func))
        return out

    def pass_condition(self, t: Target):
        path, lineno, call, names, bundle = t.payload
        described = len(call.args) >= 2 or "description" in call.keywords
        if described:
            return Satisfied(f"{path}:{lineno} gives the configuration item a description")
        documentation = _documentation_text(bundle)
        for name in names:
            if name and re.search(rf"\b{re.escape(name)}\b", documentation):
                return Satisfied(f"the contribution's documentation mentions `{name}`")
        return Violated(f"{path}:{lineno} adds a configuration option with neither a "
                        f"description nor a mention in the documentation")


# --- C and Cython extensions -----------------------------------------------------------


def _cython_sources(bundle: EvidenceBundle) -> list[str]:
    return _touched_paths(bundle, lambda p: p.endswith(".pyx"))


def _c_sources(bundle: EvidenceBundle) -> list[str]:
    return _touched_paths(bundle, lambda p: p.endswith(".c") and not p.startswith(CEXTERN))


@rule(
    id="ASTROPY-C122",
    category=CATEGORY,
    ownership="touched",  # spec §4.3 -- the extension is what the agent worked on
    reads=("files",),  # spec §5: which files were committed is the whole question
    heuristic=True,
)
class CythonSourcesAreCommitted:
    """Pre-condition: the contribution includes a Cython extension.
    Pass condition: a ``.pyx`` source is among the files it commits.

    Heuristic on the **pre-condition** (§6.3): the build is not run here, so *a Cython
    extension* is approximated by the traces one leaves in a patch -- a ``.pyx`` file, a
    ``.c`` file that says Cython generated it, or a ``setup_package.py`` naming a ``.pyx``.
    A contribution with none of those finds no target, which is the honest reading for the
    overwhelming majority of runs.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        pyx = _cython_sources(b)
        generated = [p for p in _c_sources(b)
                     if CYTHON_GENERATED.search(b.files[p].head_text or "")]
        named = [p for p in _touched_paths(b, _is_setup_package)
                 if ".pyx" in ((b.files[p].head_text or "") + added_text(b, p))]
        if not (pyx or generated or named):
            return []
        evidence = (pyx + generated + named)[0]
        return [target(f"cython-source:{b.instance_id}", evidence, None, (b, pyx, evidence),
                       f"Cython extension evidenced by {evidence}")]

    def pass_condition(self, t: Target):
        bundle, pyx, evidence = t.payload
        if pyx:
            return Satisfied(f"the contribution commits {pyx[0]}")
        return Violated(f"{evidence} shows a Cython extension and no .pyx source is "
                        f"committed")


@rule(
    id="ASTROPY-C123",
    category=CATEGORY,
    ownership="created",  # spec §4.1 -- committing a file is bringing it into the tree
    reads=("files",),  # spec §5
    heuristic=True,
)
class GeneratedCFilesAreNotCommitted:
    """Pre-condition: each C source file the agent committed under ``astropy/``.
    Pass condition: it is not a file Cython generated.

    Selecting every committed ``.c`` file, rather than the generated ones, is what lets a
    hand-written C extension record a pass (§7.1).

    Heuristic on the **pass condition** (§6.2): *generated by Cython* is recognised by the
    banner Cython writes into its output, or by a committed ``.pyx`` with the same stem. A
    generated file stripped of its banner and committed without its source reads as
    hand-written.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        return [target(f"generated-c:{path}", path, None, (path, b), path)
                for path in _added_paths(b, lambda p: p.endswith(".c")
                                         and p.startswith(PACKAGE))]

    def pass_condition(self, t: Target):
        path, bundle = t.payload
        text = bundle.files[path].head_text or ""
        if CYTHON_GENERATED.search(text):
            return Violated(f"{path} carries Cython's generated-file banner and should not "
                            f"be committed")
        sibling = path[:-2] + ".pyx"
        if sibling in bundle.files:
            return Violated(f"{path} is the C file Cython generates from {sibling} and "
                            f"should not be committed")
        return Satisfied(f"{path} is not a Cython-generated C file")


@rule(
    id="ASTROPY-C124",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5
    heuristic=True,
)
class ExternalCLibrariesAreBundled:
    """Pre-condition: each C source the agent wrote that includes a header from outside the
    C standard library and outside Python's own.
    Pass condition: the contribution also bundles that library's source under ``cextern/``.

    The sentence's condition -- *provided the licence for the C library is compatible* --
    is a fact about the library and not about the patch, so it is **not** checked: a
    contribution that correctly declined to bundle an incompatibly-licensed library reads
    as a violation here. That is the reason for the ``heuristic`` flag together with the
    proxy for "depends on an external library", which is the ``#include`` line.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        out = []
        for path in _touched_paths(b, lambda p: p.endswith((".c", ".h"))
                                   and p.startswith(PACKAGE)):
            text = (b.files[path].head_text or "") + "\n" + added_text(b, path)
            external = [m.group(1) for m in NON_STANDARD_INCLUDE.finditer(text)
                        if m.group(1) not in STANDARD_HEADERS and "/" not in m.group(1)
                        and not m.group(1).startswith(("astropy", "numpy", "_"))]
            if external:
                out.append(target(f"bundle:{path}", path, None, (path, external[0], b),
                                  f"includes {external[0]}"))
        return out

    def pass_condition(self, t: Target):
        path, header, bundle = t.payload
        bundled = [p for p in sorted(bundle.files) if p.startswith(CEXTERN)]
        if bundled:
            return Satisfied(f"the contribution bundles {bundled[0]}")
        return Violated(f"{path} depends on the external header `{header}` and no library "
                        f"source is bundled under {CEXTERN}")


@rule(
    id="ASTROPY-C125",
    category=CATEGORY,
    ownership="touched",  # spec §4.3 -- the bundled library is what the agent added
    reads=("files",),  # spec §5
)
class BundledLibrariesCanBeReplacedBySystemCopies:
    """Pre-condition: the contribution adds or edits a bundled C library under
    ``cextern/``.
    Pass condition: something in it names an ``ASTROPY_USE_SYSTEM_<LIB>`` environment
    variable.

    Not heuristic: both halves are exact. The antecedent is a path prefix the project fixes
    for bundled sources, and the pass condition is the presence of a variable whose spelling
    the sentence gives. What it does not check is that the build actually honours the
    variable, which is stated here rather than papered over with a flag.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        bundled = _touched_paths(b, lambda p: p.startswith(CEXTERN))
        if not bundled:
            return []
        return [target(f"use-system:{b.instance_id}", bundled[0], None, (b, bundled),
                       f"{len(bundled)} bundled file(s), e.g. {bundled[0]}")]

    def pass_condition(self, t: Target):
        bundle, bundled = t.payload
        for path in sorted(bundle.files):
            text = (bundle.files[path].head_text or "") + "\n" + added_text(bundle, path)
            if match := USE_SYSTEM.search(text):
                return Satisfied(f"{path} names {match.group(0)}")
        return Violated(f"{bundled[0]} bundles a C library with no "
                        f"ASTROPY_USE_SYSTEM_<LIB> opt-out anywhere in the contribution")


@rule(
    id="ASTROPY-C225",
    category=CATEGORY,
    ownership="touched",  # spec §4.3 -- the function the agent wrote or edited
    reads=("files",),  # spec §5
    heuristic=True,
)
class GetExtensionsReturnsExtensionObjects:
    """Pre-condition: each ``get_extensions`` function the agent wrote or edited in a
    ``setup_package.py``.
    Pass condition: it returns a list, and builds ``Extension`` objects to put in it.

    Heuristic on the **pass condition** (§6.2): what a function returns at run time is not
    decidable from its text, so this reads the shape -- a ``return`` of a list or of a name,
    with an ``Extension`` construction somewhere in the body. A function that delegates the
    construction to a helper reads as a violation.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        out = []
        for path, module in modules(b):
            if not _is_setup_package(path):
                continue
            for function in module.functions:
                if function.name != GET_EXTENSIONS:
                    continue
                if own.owns_span(b, path, function.span(), "touched"):
                    out.append(target(f"get-extensions:{path}:{function.lineno}", path,
                                      function.span(), (path, function), function.name))
        return out

    def pass_condition(self, t: Target):
        path, function = t.payload
        body = ast.dump(function.node)
        returns = [n for n in ast.walk(function.node) if isinstance(n, ast.Return)]
        if not returns:
            return Violated(f"{path}:{function.lineno} get_extensions returns nothing")
        if "Extension" not in body:
            return Violated(f"{path}:{function.lineno} get_extensions builds no "
                            f"setuptools.Extension object")
        if not any(isinstance(r.value, (ast.List, ast.Name, ast.ListComp)) for r in returns):
            return Violated(f"{path}:{function.lineno} get_extensions does not return a "
                            f"list")
        return Satisfied(f"{path}:{function.lineno} get_extensions returns a list of "
                         f"Extension objects")


@rule(
    id="ASTROPY-C226",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5
    heuristic=True,
)
class CExtensionsAreDefinedThroughGetExtensions:
    """Pre-condition: the contribution adds or edits a C extension source under
    ``astropy/``.
    Pass condition: a ``setup_package.py`` in the contribution defines ``get_extensions``.

    Heuristic on the **pre-condition** (§6.3): *a C extension* is approximated by a ``.c``
    or ``.h`` file inside the package, which is what one looks like in a patch. A C
    extension added without any C source -- there is no such thing -- would be missed; a
    C file that is not part of an extension is over-selected.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        sources = _touched_paths(b, lambda p: p.endswith((".c", ".h"))
                                 and p.startswith(PACKAGE))
        if not sources:
            return []
        return [target(f"c-extension:{b.instance_id}", sources[0], None, (b, sources),
                       f"{len(sources)} C source(s), e.g. {sources[0]}")]

    def pass_condition(self, t: Target):
        bundle, sources = t.payload
        for path, module in modules(bundle):
            if _is_setup_package(path) and any(f.name == GET_EXTENSIONS
                                               for f in module.functions):
                return Satisfied(f"{path} defines {GET_EXTENSIONS}()")
        return Violated(f"{sources[0]} adds a C extension source and no setup_package.py "
                        f"in the contribution defines {GET_EXTENSIONS}()")


@rule(
    id="ASTROPY-C227",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5
    heuristic=True,
)
class CythonExtensionsNameThePyxAsSource:
    """Pre-condition: each ``Extension(...)`` the agent wrote for a Cython module.
    Pass condition: its sources name the ``.pyx`` file rather than the generated ``.c``.

    Heuristic on the **pre-condition** (§6.3): *a Cython extension* is recognised by the
    extension naming a ``.pyx`` source, or naming a ``.c`` whose stem matches a ``.pyx``
    the contribution carries. An extension whose Cython origin is visible only to the build
    system is not selected.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        pyx_stems = {p[:-4].rsplit("/", 1)[-1] for p in _cython_sources(b)}
        out = []
        for path, module, call in _extension_calls(b):
            literals = _string_args(call)
            names_pyx = [text for text in literals if text.endswith(".pyx")]
            names_c = [text for text in literals if text.endswith(".c")
                       and text[:-2].rsplit("/", 1)[-1] in pyx_stems]
            if names_pyx or names_c:
                out.append(target(f"pyx-source:{path}:{call.lineno}", path,
                                  (call.lineno, call.lineno),
                                  (path, call.lineno, names_pyx, names_c),
                                  ", ".join(names_pyx + names_c)))
        return out

    def pass_condition(self, t: Target):
        path, lineno, names_pyx, names_c = t.payload
        if names_c:
            return Violated(f"{path}:{lineno} gives the generated `{names_c[0]}` as the "
                            f"extension source rather than the .pyx file")
        return Satisfied(f"{path}:{lineno} gives `{names_pyx[0]}` as the extension source")


@rule(
    id="ASTROPY-C228",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5
    heuristic=True,
)
class NumpyHeadersComeFromGetInclude:
    """Pre-condition: each ``Extension(...)`` the agent wrote in a ``setup_package.py``
    that mentions numpy.
    Pass condition: its include directories come from ``numpy.get_include()``.

    Heuristic on the **pre-condition** (§6.3): *uses numpy at the C level* is approximated
    by the setup file mentioning numpy at all, which is the only trace a patch carries.
    An extension that needs the headers without the file naming numpy is not selected.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        out = []
        for path, module, call in _extension_calls(b):
            text = module.source
            if "numpy" not in text:
                continue
            out.append(target(f"numpy-include:{path}:{call.lineno}", path,
                              (call.lineno, call.lineno), (path, call.lineno, module, call),
                              call.func))
        return out

    def pass_condition(self, t: Target):
        path, lineno, module, call = t.payload
        includes = call.keywords.get("include_dirs")
        source = ast.dump(includes) if includes is not None else ""
        if "get_include" in source:
            return Satisfied(f"{path}:{lineno} takes its include directory from "
                             f"numpy.get_include()")
        if includes is None and "get_include" in module.source:
            return Satisfied(f"{path} calls numpy.get_include() for its include directories")
        return Violated(f"{path}:{lineno} builds a numpy extension without using "
                        f"numpy.get_include() for the headers")


@rule(
    id="ASTROPY-C229",
    category=CATEGORY,
    ownership="created",  # spec §4.1 -- where a header goes is decided when it is added
    reads=("files",),  # spec §5
    heuristic=True,
)
class InstallableHeadersLiveInAnIncludeDirectory:
    """Pre-condition: each C header the agent added inside ``astropy/``.
    Pass condition: it sits in an ``include`` directory inside its package.

    Heuristic on the **pre-condition** (§6.3): the sentence is about headers that are
    *installed* for third-party C code to link against, and whether a header is meant to be
    installed is not written in the patch. Every added header is selected, so a private
    header kept beside its implementation reads as a violation.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        return [target(f"header-dir:{path}", path, None, path, path)
                for path in _added_paths(b, lambda p: p.endswith(".h")
                                         and p.startswith(PACKAGE))]

    def pass_condition(self, t: Target):
        path = t.payload
        if INCLUDE_DIR in path:
            return Satisfied(f"{path} is in an include directory inside its package")
        return Violated(f"{path} is a header outside any `include` directory")


@rule(
    id="ASTROPY-C230",
    category=CATEGORY,
    ownership="touched",  # spec §4.3 -- the declaration accompanies the header
    reads=("files",),  # spec §5
    heuristic=True,
)
class InstallableHeadersAreDeclaredAsPackageData:
    """Pre-condition: each C header the agent added in an ``include`` directory inside the
    package.
    Pass condition: ``pyproject.toml`` declares it under
    ``[tool.setuptools.package_data]``.

    Heuristic on the **pass condition** (§6.2): the declaration is a glob, so this checks
    that the section exists and that a pattern in the contribution's ``pyproject.toml``
    could cover the header -- the package's own name, or an ``include/`` pattern. It does
    not expand globs, so a correct but unusual pattern reads as a violation.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        return [target(f"header-data:{path}", path, None, (path, b), path)
                for path in _added_paths(b, lambda p: p.endswith(".h")
                                         and INCLUDE_DIR in p and p.startswith(PACKAGE))]

    def pass_condition(self, t: Target):
        path, bundle = t.payload
        change = bundle.files.get(PYPROJECT)
        text = ((change.head_text or "") + added_text(bundle, PYPROJECT)) if change else ""
        if PACKAGE_DATA_SECTION not in text:
            return Violated(f"{path} is an installable header and {PYPROJECT} carries no "
                            f"{PACKAGE_DATA_SECTION} section in this contribution")
        package = ".".join(path.split("/")[:-2])
        if "include/" in text or package in text:
            return Satisfied(f"{PYPROJECT} declares {path} under {PACKAGE_DATA_SECTION}")
        return Violated(f"{PACKAGE_DATA_SECTION} in {PYPROJECT} declares no pattern "
                        f"covering {path}")


@rule(
    id="ASTROPY-C231",
    category=CATEGORY,
    ownership="touched",  # spec §4.3 -- no newness qualifier; an edited file is in scope
    reads=("files",),  # spec §5
)
class SetupPackageDoesNotImportItsPackage:
    """Pre-condition: each ``setup_package.py`` the agent wrote or edited.
    Pass condition: it imports nothing from the package it belongs to.

    Not heuristic: the import table says exactly what a module imports, and "from the
    package it belongs to" is decided by the top-level name and by whether the import is
    relative -- both read off the syntax tree. A ``setup_package.py`` that imports only
    third-party build tooling passes.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        return [target(f"setup-import:{path}", path, None, (path, module), path)
                for path, module in modules(b) if _is_setup_package(path)]

    def pass_condition(self, t: Target):
        path, module = t.payload
        for node in ast.walk(module.tree):
            if isinstance(node, ast.ImportFrom) and node.level:
                return Violated(f"{path}:{node.lineno} imports relatively from its own "
                                f"package, which triggers an import at build time")
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                names = ([alias.name for alias in node.names]
                         if isinstance(node, ast.Import) else [node.module or ""])
                for name in names:
                    if name.split(".")[0] == "astropy":
                        return Violated(f"{path}:{node.lineno} imports `{name}` from the "
                                        f"package it belongs to")
        return Satisfied(f"{path} imports nothing from astropy")


# --- command-line scripts ---------------------------------------------------------------


def _script_modules(bundle: EvidenceBundle, *, mode: str = "touched"):
    for path, module in modules(bundle, mode=mode):
        if _is_script_module(path, module):
            yield path, module


@rule(
    id="ASTROPY-C233",
    category=CATEGORY,
    ownership="touched",  # spec §4.3 -- an edited script must have the same shape
    reads=("files",),  # spec §5
    heuristic=True,
)
class ScriptsHaveAMainThatDelegates:
    """Pre-condition: each command-line script the agent wrote or edited.
    Pass condition: it defines ``main``, and ``main`` calls a library function rather than
    doing the work itself.

    Heuristic on **both layers** (§6.1). *A command-line script* is approximated by a
    module under a ``scripts/`` directory or one carrying an ``if __name__ ==
    "__main__"`` block. *Delegates to a library function* is approximated by ``main``
    calling something that is not argument parsing -- which a script whose work genuinely
    is one call would satisfy trivially, and which a well-factored ``main`` written as a
    single expression could fail.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        return [target(f"script-main:{path}", path, None, (path, module), path)
                for path, module in _script_modules(b)]

    def pass_condition(self, t: Target):
        path, module = t.payload
        main = next((f for f in module.functions if f.name == "main"
                     and f.qualname == f.name), None)
        if main is None:
            return Violated(f"{path} is a command-line script with no `main` function")
        calls = [c for c in module.calls_within(main.span())
                 if c.func.split(".")[-1] not in ("ArgumentParser", "add_argument",
                                                  "parse_args", "main")]
        if not calls:
            return Violated(f"{path}:{main.lineno} `main` parses arguments and calls no "
                            f"library function")
        return Satisfied(f"{path}:{main.lineno} `main` delegates to "
                         f"`{calls[0].func}`")


@rule(
    id="ASTROPY-C234",
    category=CATEGORY,
    ownership="touched",  # spec §4.3
    reads=("files",),  # spec §5
    heuristic=True,
)
class MainTakesOneOptionalArgument:
    """Pre-condition: each ``main`` function the agent wrote or edited in a command-line
    script.
    Pass condition: it takes a single argument, and that argument has a default.

    Heuristic on the **pass condition** (§6.2): the signature is read exactly, but the
    sentence also says the argument *holds* ``sys.argv[1:]``, and what a caller passes is
    not decidable from the definition. A one-argument ``main`` used for something else
    passes.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        out = []
        for path, module in _script_modules(b):
            for function in module.functions:
                if function.name != "main" or function.qualname != function.name:
                    continue
                if own.owns_span(b, path, function.span(), "touched"):
                    out.append(target(f"main-signature:{path}:{function.lineno}", path,
                                      function.span(), (path, function), "main"))
        return out

    def pass_condition(self, t: Target):
        path, function = t.payload
        args = function.node.args
        positional = list(args.posonlyargs) + list(args.args)
        if len(positional) != 1 or args.vararg is not None:
            return Violated(f"{path}:{function.lineno} `main` takes "
                            f"{len(positional)} argument(s); it should take one")
        if not args.defaults:
            return Violated(f"{path}:{function.lineno} `main`'s argument has no default, "
                            f"so it is not optional")
        return Satisfied(f"{path}:{function.lineno} `main` takes one optional argument")


@rule(
    id="ASTROPY-C235",
    category=CATEGORY,
    ownership="created",  # spec §4.1 -- registering accompanies adding the script
    reads=("files",),  # spec §5: the packaging configuration is a file in the patch
    heuristic=True,
)
class ScriptsAreRegisteredAsEntryPoints:
    """Pre-condition: each command-line script the agent added.
    Pass condition: the packaging configuration in the contribution names it as an entry
    point.

    Heuristic on the **pass condition** (§6.2): a registration outside the contribution
    cannot be seen, so a script added to a package whose entry points were already declared
    reads as a violation. The corpus records that the prose says ``setup.py`` while the
    example on the same page says ``pyproject.toml``; both are accepted, and ``setup.cfg``
    with them, because which file holds the entry points is a packaging detail the rule
    does not turn on.
    """

    def precondition(self, b: EvidenceBundle) -> list[Target]:
        return [target(f"entry-point:{path}", path, None, (path, b), path)
                for path, module in _script_modules(b, mode="created")]

    def pass_condition(self, t: Target):
        path, bundle = t.payload
        text = _packaging_text(bundle)
        module_name = path[:-3].replace("/", ".")
        if module_name in text:
            return Satisfied(f"the packaging configuration names `{module_name}`")
        if "[project.scripts]" in text or "console_scripts" in text or "entry_points" in text:
            return Satisfied("the contribution declares script entry points")
        return Violated(f"{path} adds a command-line script and no packaging configuration "
                        f"in the contribution registers it as an entry point")
