#!/usr/bin/env python3
"""The scored batch of a repo, as a work list -- and, on request, as stub modules.

    python tools/scaffold_checkers.py --repo sphinx-doc            # the work list
    python tools/scaffold_checkers.py --repo sphinx-doc --emit     # write stub modules
    python tools/scaffold_checkers.py --repo sphinx-doc --check    # corpus vs pack drift

**The default mode writes nothing.** It prints every rule in `Care AND must` grouped by
Shared Category, with the metadata `docs/checker-authoring.md` proposes for it. That is
the whole job most of the time: the expensive part of a predicate is deciding what
satisfies the rule, and no generator can do that. What a person loses track of over 24
rules is *which ones are left*, and a printed list fixes it.

`--emit` exists for the other half -- transcription. Rule IDs, category constants and
corpus sentences retyped by hand are how a predicate ends up grading the wrong sentence,
and `docs/rule-index.md` only catches that if the docstring is faithful. Emitting them
from the workbook makes the corpus, not somebody's memory, the specification.

**The defaults it prints are a prior, not an answer.** `docs/checker-authoring.md` §4-6
gives the decision rules -- which are about the corpus sentence, not about what previous
packs happened to do. The constants below are only the most common outcome of applying
those rules so far, regenerated by `--priors` into `docs/checker-priors.md`, which flags
every category carried by a single repository. Every emitted decorator carries a
`confirm` comment. Accepting a default without reading the rule is the failure mode this
tool introduces, and the reason the default mode does not write code.

**It never adds anything to `RULE_MODULES`.** A registered stub satisfies
`test_implemented_categories_are_complete` -- the category looks complete and the suite
goes green over a pack that computes nothing. Registration stays a deliberate one-line
edit that means "this pack is finished". See §10 of the authoring doc.

Offline, reads only the workbook, and refuses to overwrite a file that exists.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from compliance.core.registry import (  # noqa: E402
    PROJECT_ROOT,
    CorpusRule,
    corpus_path_for,
    in_batch,
    load_corpus,
)

#: Shared Category -> rule-pack module. 1:1 and exact in both existing packs (220/220);
#: kept in sync with CATEGORIES in tools/corpus.py and CATEGORY_ORDER in
#: rules/build_contributing_rules.py. A category outside this map is an error, not a
#: new module -- inventing one silently is how a repo ends up with a category no
#: aggregation knows about.
CATEGORY_MODULE = {
    "Git and commit conventions": "git_conventions",
    "PR and release metadata": "pr_metadata",
    "Tests and test style": "tests",
    "Specialized changes": "specialized",
    "Documentation and docstrings": "documentation",
    "AI-assisted contribution policy": "ai_policy",
    "Code and quality": "code_quality",
    "Language and framework style": "language_style",
}

#: Most common ownership per category so far, with the count that agreed -- a starting
#: guess for the emitted decorator, superseded by §4 of the authoring doc whenever the
#: sentence disagrees. Regenerate with `--priors`; several categories are carried by one
#: repository and their agreement rates mean little.
OWNERSHIP_DEFAULT = {
    "AI-assisted contribution policy": ("created", 9, 10),
    "Code and quality": ("touched", 6, 6),
    "Documentation and docstrings": ("touched", 43, 55),
    "Git and commit conventions": ("created", 11, 16),
    "Language and framework style": ("touched", 41, 41),
    "PR and release metadata": ("created", 22, 23),
    "Specialized changes": ("touched", 32, 33),
    "Tests and test style": ("touched", 26, 36),
}

#: Most common `reads` per category so far, same caveat. `files` is the fallback because
#: most rules are decidable from the patch; §5 of the authoring doc derives it properly.
READS_DEFAULT = {
    "AI-assisted contribution policy": ("files", "pr_text"),
    "Code and quality": ("files",),
    "Documentation and docstrings": ("files",),
    "Git and commit conventions": ("commits",),
    "Language and framework style": ("files",),
    "PR and release metadata": ("pr_text",),
    "Specialized changes": ("files",),
    "Tests and test style": ("files",),
}

#: CheckTier refines `reads` rather than replacing it. `differential` needs whichever
#: Phase 5 run source the rule is about, which the sentence names and this cannot guess.
TIER_EXTRA = {
    "trajectory": ("commands",),
    "differential": (),
}

_STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "in", "into", "is",
    "it", "its", "must", "not", "of", "on", "or", "should", "that", "the", "their",
    "them", "there", "they", "this", "to", "when", "which", "with", "you", "your",
}


def package_name(slug: str) -> str:
    """`scikit-learn` -> `scikit_learn`.

    Four of the twelve slugs are not Python identifiers. The *directory* under `rules/`
    and the *ID prefix* keep the hyphen -- `tests/test_registry.py` selects on
    `slug.upper() + "-"` and `tools/audit_rules.py` derives the prefix from the
    directory name -- so only the package name is transformed. Changing any of the other
    two fails silently: the completeness test iterates categories that already have a
    checker, so with no matching prefix it passes vacuously over an empty selection.
    """
    return slug.replace("-", "_")


def batch(repo: str) -> list[CorpusRule]:
    corpus = load_corpus(corpus_path_for(repo))
    return [corpus[rule_id] for rule_id in in_batch(corpus)]


def grouped(rules: list[CorpusRule]) -> dict[str, list[CorpusRule]]:
    out: dict[str, list[CorpusRule]] = {}
    for rule in rules:
        if rule.shared_category not in CATEGORY_MODULE:
            raise SystemExit(
                f"{rule.id}: Shared Category {rule.shared_category!r} is outside the "
                f"taxonomy. Fix the workbook -- do not add a module for it."
            )
        out.setdefault(rule.shared_category, []).append(rule)
    return {k: out[k] for k in CATEGORY_MODULE if k in out}


def defaults(rule: CorpusRule) -> tuple[str, tuple[str, ...], int, int]:
    ownership, agreed, total = OWNERSHIP_DEFAULT[rule.shared_category]
    reads = list(READS_DEFAULT[rule.shared_category])
    for extra in TIER_EXTRA.get(rule.check_tier, ()):
        if extra not in reads:
            reads.append(extra)
    if rule.check_tier == "differential" and "files" not in reads:
        reads.append("files")
    return ownership, tuple(reads), agreed, total


def class_name(rule: CorpusRule, taken: set[str]) -> str:
    words = [w for w in re.findall(r"[A-Za-z]+", rule.atomic_rule)
             if w.lower() not in _STOPWORDS]
    name = "".join(w[:1].upper() + w[1:].lower() for w in words[:4]) or "Rule"
    if not name[0].isalpha():
        name = "Rule" + name
    if name in taken:
        name = f"{name}{rule.id.rsplit('-', 1)[-1]}"
    taken.add(name)
    return name


# --------------------------------------------------------------------------- list


def cmd_list(repo: str) -> int:
    rules = batch(repo)
    print(f"\n{repo}: {len(rules)} rules in the scored batch (Care AND must)\n")
    for category, members in grouped(rules).items():
        print(f"  {category}  ->  compliance/rules/{package_name(repo)}/"
              f"{CATEGORY_MODULE[category]}.py  [{len(members)}]")
        for rule in members:
            ownership, reads, agreed, total = defaults(rule)
            print(f"    {rule.id}  {rule.check_tier or '(no tier)':<12} "
                  f"ownership={ownership} ({agreed}/{total})  reads={reads}")
            print(f"        {rule.atomic_rule}")
        print()
    tiers: dict[str, int] = {}
    for rule in rules:
        tiers[rule.check_tier or "(none)"] = tiers.get(rule.check_tier or "(none)", 0) + 1
    print("  tiers: " + ", ".join(f"{k}={v}" for k, v in sorted(tiers.items())))
    print(f"  defaults above are a prior measured from the {_committed_count()} "
          "committed predicates;")
    print("  read docs/checker-authoring.md before accepting any of them.\n")
    return 0


# --------------------------------------------------------------------------- emit


MODULE_HEADER = '''"""{display}: {category} -- {count} rules.

Layer C. Every rule is two layers (docs/checker-authoring.md §2): ``precondition`` selects
on the rule's ANTECEDENT, ``pass_condition`` grades.

SCAFFOLDED -- the metadata below is the prior from docs/checker-authoring.md, not a
decision. Confirm every ``ownership`` and ``reads`` against the corpus sentence, replace
each raising body, and delete this paragraph when the module is finished.
"""

from __future__ import annotations

from compliance.core.models import (EvidenceBundle, Satisfied, Target, Undetermined,
                                    Violated)
from compliance.core.registry import rule

CATEGORY = "{category}"
'''

RULE_TEMPLATE = '''

@rule(
    id="{rid}",
    category=CATEGORY,
    ownership="{ownership}",  # confirm: category prior, {agreed}/{total} of the committed pack
    reads={reads},  # confirm: CheckTier={tier} is a cross-check, not the answer (§5)
    # TODO(heuristic): §6 is a test, not a default -- add heuristic=True if the pass
    # condition is a proxy, then delete this line. `--check` reports rules that still
    # carry it, because a silent False is how an undeclared proxy ships.
)
class {cls}:
    """Pre-condition: TODO -- the situation that invokes this rule, not the artefact it
    demands (§4.2).
    Pass condition: TODO -- what satisfies it.

    Corpus: {sentence}
    Source: {source}
    """

    def precondition(self, bundle: EvidenceBundle) -> list[Target]:
        raise NotImplementedError("{rid} precondition")

    def pass_condition(self, target: Target):
        raise NotImplementedError("{rid} pass_condition")
'''

TEST_HEADER = '''"""Three cases per rule (docs/checker-authoring.md §9): one target that satisfies the
pass condition, one that violates it, and one input where the pre-condition finds
nothing.

The third case is the one that catches a pre-condition written against the artefact the
rule demands instead of the antecedent that invokes it (§4.2). Do not skip it.

SCAFFOLDED -- every test below fails until it is written.
"""

from __future__ import annotations

import pytest
from conftest import make_bundle, make_commit, make_file  # noqa: F401

from compliance.core.registry import registered
from compliance.core.runner import run_rule

import compliance.rules.{pkg}.{module}  # noqa: F401,E402  (registers the rules)

RULES = {{r.id: r for r in registered()}}


def verdict(rule_id, bundle, corpus):
    return run_rule(bundle, RULES[rule_id], corpus)
'''

TEST_TEMPLATE = '''

# --- {rid} {sentence} ---


def test_{stem}_passes_when(corpus):
    pytest.fail("not written: {rid} satisfied case")


def test_{stem}_fails_when(corpus):
    pytest.fail("not written: {rid} violated case")


def test_{stem}_finds_no_target_when(corpus):
    pytest.fail("not written: {rid} no-target case")
'''


def cmd_emit(repo: str, force: bool) -> int:
    pkg = package_name(repo)
    display = repo
    pkg_dir = PROJECT_ROOT / "compliance" / "rules" / pkg
    tests_dir = PROJECT_ROOT / "tests"
    rules = batch(repo)
    groups = grouped(rules)

    planned: list[tuple[Path, str]] = []
    init = pkg_dir / "__init__.py"
    if not init.exists():
        planned.append((init, f'"""{display} rule pack. Layer C."""\n'))

    for category, members in groups.items():
        module = CATEGORY_MODULE[category]
        taken: set[str] = set()
        body = MODULE_HEADER.format(display=display, category=category,
                                    count=len(members))
        test_body = TEST_HEADER.format(pkg=pkg, module=module)
        for rule in members:
            ownership, reads, agreed, total = defaults(rule)
            cls = class_name(rule, taken)
            body += RULE_TEMPLATE.format(
                rid=rule.id, ownership=ownership, agreed=agreed, total=total,
                reads=repr(reads), tier=rule.check_tier or "(none)", cls=cls,
                sentence=rule.atomic_rule.replace("\\n", " "),
                source=rule.source or "(none recorded)",
            )
            stem = rule.id.rsplit("-", 1)[-1].lower()
            test_body += TEST_TEMPLATE.format(
                rid=rule.id, stem=stem,
                sentence=rule.atomic_rule.replace("\\n", " ")[:70],
            )
        planned.append((pkg_dir / f"{module}.py", body))
        planned.append((tests_dir / f"test_{pkg}_{module}.py", test_body))

    existing = [path for path, _ in planned if path.exists()]
    if existing and not force:
        print("refusing to overwrite:", file=sys.stderr)
        for path in existing:
            print(f"  {path.relative_to(PROJECT_ROOT)}", file=sys.stderr)
        print("\nThese hold written predicates. Use --check to see corpus/pack drift, "
              "or --force if you are certain.", file=sys.stderr)
        return 1

    pkg_dir.mkdir(parents=True, exist_ok=True)
    for path, text in planned:
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(PROJECT_ROOT)}")

    print(f"\n{len(rules)} stubs across {len(groups)} modules. Nothing is registered:")
    print(f'  add "{repo}" to RULE_MODULES in compliance/cli.py only when a module\'s')
    print("  predicates are written -- a registered stub makes the completeness test "
          "pass\n  over a pack that computes nothing.")
    return 0


# --------------------------------------------------------------------------- check


def cmd_check(repo: str) -> int:
    """Corpus against pack, without importing anything.

    Read with `ast` rather than the registry so an unregistered pack -- the normal state
    of a pack being written -- can still be checked.
    """
    pkg_dir = PROJECT_ROOT / "compliance" / "rules" / package_name(repo)
    if not pkg_dir.exists():
        print(f"{pkg_dir.relative_to(PROJECT_ROOT)} does not exist yet")
        return 1

    in_pack: dict[str, str] = {}
    stubbed: set[str] = set()
    undecided: set[str] = set()
    for path in sorted(pkg_dir.glob("*.py")):
        if path.name == "__init__.py":
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            for decorator in node.decorator_list:
                if not (isinstance(decorator, ast.Call)
                        and getattr(decorator.func, "id", None) == "rule"):
                    continue
                keywords = {k.arg: k.value for k in decorator.keywords}
                rid = None
                if decorator.args:
                    rid = getattr(decorator.args[0], "value", None)
                if "id" in keywords:
                    rid = getattr(keywords["id"], "value", None)
                if rid:
                    in_pack[rid] = path.name
                    if "NotImplementedError" in ast.dump(node):
                        stubbed.add(rid)
        for marker_id in re.findall(r'id="([^"]+)"[^)]*?TODO\(heuristic\)',
                                    path.read_text(encoding="utf-8"), re.S):
            undecided.add(marker_id)

    wanted = {rule.id for rule in batch(repo)}
    missing = sorted(wanted - set(in_pack))
    extra = sorted(set(in_pack) - wanted)

    print(f"\n{repo}: batch {len(wanted)}, in pack {len(in_pack)}, "
          f"still stubs {len(stubbed)}, heuristic undecided {len(undecided)}")
    for label, ids in (("in the batch, not in the pack", missing),
                       ("in the pack, not in the batch", extra),
                       ("stubs still raising", sorted(stubbed)),
                       ("heuristic still undecided", sorted(undecided))):
        if ids:
            print(f"\n  {label}:")
            for rid in ids:
                print(f"    {rid}  ({in_pack.get(rid, '')})")
    if not missing and not extra and not stubbed and not undecided:
        print("\n  complete -- safe to add to RULE_MODULES.\n")
        return 0
    print()
    return 1


# --------------------------------------------------------------------------- priors


def _implemented_repos() -> list[tuple[str, Path]]:
    """Every repo that has both a corpus and a rule pack, by slug."""
    out = []
    for repo_dir in sorted((PROJECT_ROOT / "rules").iterdir()):
        if not (repo_dir / "repo.conf").exists():
            continue
        pkg_dir = PROJECT_ROOT / "compliance" / "rules" / package_name(repo_dir.name)
        if pkg_dir.is_dir() and any(pkg_dir.glob("*.py")):
            out.append((repo_dir.name, pkg_dir))
    return out


def _decorators(pkg_dir: Path) -> dict[str, dict]:
    """`@rule(...)` metadata read with `ast`, so nothing has to be importable."""
    found: dict[str, dict] = {}
    for path in sorted(pkg_dir.glob("*.py")):
        if path.name == "__init__.py":
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            for decorator in node.decorator_list:
                if not (isinstance(decorator, ast.Call)
                        and getattr(decorator.func, "id", None) == "rule"):
                    continue
                keywords = {k.arg: k.value for k in decorator.keywords}

                def literal(key, fallback=None):
                    if key not in keywords:
                        return fallback
                    try:
                        return ast.literal_eval(keywords[key])
                    except (ValueError, SyntaxError):
                        return None

                rid = getattr(decorator.args[0], "value", None) if decorator.args else None
                rid = literal("id", rid)
                if rid:
                    found[rid] = {
                        "module": path.stem,
                        "ownership": literal("ownership", "touched"),
                        "heuristic": bool(literal("heuristic", False)),
                        "reads": tuple(literal("reads", ()) or ()),
                    }
    return found


def _committed_count() -> int:
    """How many predicates the priors in `defaults()` were measured from.

    Counted rather than hardcoded: the number moved from 220 to 823 the moment the
    remaining ten packs landed, and a stale figure here understates the evidence behind
    every default this tool prints.
    """
    return sum(len(_decorators(pkg_dir)) for _, pkg_dir in _implemented_repos())


def cmd_priors(write: bool) -> int:
    """Regenerate the metadata priors from every committed pack.

    Generated rather than written, for the reason `tools/rule_index.py` is: a hand-kept table drifts the moment a pack lands, and a
    drifted table is worse than none because it still looks authoritative.

    The repo-split column is the point. A category carried by one repository is one
    author's habit, not a convention -- it is printed so nobody reads it as a law.
    """
    records = []
    for slug, pkg_dir in _implemented_repos():
        corpus = load_corpus(corpus_path_for(slug))
        for rid, meta in _decorators(pkg_dir).items():
            row = corpus.get(rid)
            if row is None:
                continue
            records.append({"repo": slug, "id": rid,
                            "category": row.shared_category,
                            "tier": row.check_tier, **meta})
    if not records:
        print("no committed packs to measure", file=sys.stderr)
        return 1

    repos = sorted({r["repo"] for r in records})
    categories = [c for c in CATEGORY_MODULE if any(r["category"] == c for r in records)]

    def counts(category, key):
        tally: dict = {}
        for r in records:
            if r["category"] == category:
                value = r[key]
                tally[value] = tally.get(value, 0) + 1
        return sorted(tally.items(), key=lambda kv: (-kv[1], str(kv[0])))

    lines = [
        "# Metadata priors, measured",
        "",
        "**Generated by `tools/scaffold_checkers.py --priors --write`. Do not edit.**",
        "",
        f"Computed from {len(records)} committed predicates across "
        f"{len(repos)} repositories ({', '.join(repos)}), joined to their corpus rows.",
        "",
        "These are priors for `docs/checker-authoring.md`, not rules. The **repos**",
        "column is why: a category carried by a single repository records one author's",
        "habit in one sitting, and its agreement rate means nothing. Read §4-§6 of the",
        "authoring doc for the decision rules; use this page only to see how often those",
        "rules have been departed from so far.",
        "",
        "## Ownership",
        "",
        "| Shared Category | most common | agreed | repos | spread |",
        "|---|---|---:|---|---|",
    ]
    for category in categories:
        own = counts(category, "ownership")
        total = sum(n for _, n in own)
        split = {r: sum(1 for x in records
                        if x["category"] == category and x["repo"] == r) for r in repos}
        present = [r for r in repos if split[r]]
        flag = " **(1 repo)**" if len(present) == 1 else ""
        spread = ", ".join(f"{v}={n}" for v, n in own)
        lines.append(f"| {category} | `{own[0][0]}` | {own[0][1]}/{total} | "
                     f"{', '.join(f'{r} {split[r]}' for r in present)}{flag} | {spread} |")

    lines += ["", "## Reads", "",
              "| Shared Category | most common | agreed | spread |", "|---|---|---:|---|"]
    for category in categories:
        rd = counts(category, "reads")
        total = sum(n for _, n in rd)
        spread = ", ".join(f"`{tuple(v)}`={n}" for v, n in rd[:4])
        lines.append(f"| {category} | `{tuple(rd[0][0])}` | {rd[0][1]}/{total} | {spread} |")

    lines += ["", "## Heuristic rate", "",
              "Calibration only. A category far from its neighbours is a prompt to "
              "re-read your predicates, never a target.", "",
              "| Shared Category | heuristic |", "|---|---:|"]
    for category in categories:
        members = [r for r in records if r["category"] == category]
        lines.append(f"| {category} | {sum(1 for r in members if r['heuristic'])}"
                     f"/{len(members)} |")
    total_h = sum(1 for r in records if r["heuristic"])
    per_repo = ", ".join(
        f"{r} {sum(1 for x in records if x['repo'] == r and x['heuristic'])}/"
        f"{sum(1 for x in records if x['repo'] == r)}" for r in repos)
    lines.append(f"| **all** | **{total_h}/{len(records)}** ({per_repo}) |")

    lines += ["", "## Category to module", "",
              "| Shared Category | module | exceptions |", "|---|---|---|"]
    for category in categories:
        mods = counts(category, "module")
        others = ", ".join(f"{m}={n}" for m, n in mods[1:]) or "none"
        lines.append(f"| {category} | `{mods[0][0]}.py` | {others} |")

    text = "\n".join(lines) + "\n"
    if write:
        out = PROJECT_ROOT / "docs" / "checker-priors.md"
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out.relative_to(PROJECT_ROOT)}  "
              f"({len(records)} predicates, {len(repos)} repos)")
    else:
        print(text)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo", help="slug, i.e. the rules/ directory")
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--emit", action="store_true", help="write stub modules + tests")
    action.add_argument("--check", action="store_true", help="corpus vs pack drift")
    action.add_argument("--priors", action="store_true",
                        help="recompute docs/checker-priors.md from committed packs")
    parser.add_argument("--force", action="store_true",
                        help="with --emit, overwrite existing modules")
    parser.add_argument("--write", action="store_true",
                        help="with --priors, write docs/checker-priors.md")
    args = parser.parse_args(argv)

    if args.priors:
        return cmd_priors(args.write)
    if args.emit:
        return cmd_emit(args.repo, args.force)
    if not args.repo:
        parser.error("--repo is required unless --priors is given")
    if args.check:
        return cmd_check(args.repo)
    return cmd_list(args.repo)


if __name__ == "__main__":
    raise SystemExit(main())
